namespace ReceiptRing.Config {
  export const CATEGORIES: readonly Domain.Category[] = [
    {
      name: "Groceries",
      color: "#5d7052",
      keywords: [
        "apple",
        "banana",
        "bread",
        "milk",
        "eggs",
        "yogurt",
        "cheese",
        "produce",
        "market",
        "grocery",
        "organic",
        "cereal",
        "rice",
        "pasta",
        "flour",
        "sugar",
        "butter",
        "juice",
        "chicken",
        "beef",
        "fish",
        "lettuce",
        "tomato",
        "avocado",
        "potato",
        "onion",
        "snack",
        "chips",
        "sauce",
        "water"
      ]
    },
    {
      name: "Dining",
      color: "#c18c5d",
      keywords: [
        "coffee",
        "latte",
        "burger",
        "pizza",
        "taco",
        "restaurant",
        "cafe",
        "deli",
        "sandwich",
        "salad",
        "tea",
        "bowl",
        "espresso",
        "grill",
        "bar",
        "bakery",
        "donut",
        "sushi",
        "noodle",
        "meal",
        "combo",
        "takeout"
      ]
    },
    {
      name: "Home",
      color: "#d4b060",
      keywords: [
        "detergent",
        "soap",
        "towel",
        "paper",
        "cleaner",
        "trash",
        "storage",
        "kitchen",
        "home",
        "batteries",
        "foil",
        "tissue",
        "napkin",
        "laundry",
        "dish",
        "sponge",
        "wipes",
        "bulb",
        "decor",
        "hardware",
        "garden"
      ]
    },
    {
      name: "Health",
      color: "#9a8bc0",
      keywords: [
        "vitamin",
        "pharmacy",
        "medicine",
        "rx",
        "bandage",
        "wellness",
        "protein",
        "toothpaste",
        "shampoo",
        "ibuprofen",
        "acetaminophen",
        "allergy",
        "first aid",
        "mouthwash",
        "deodorant",
        "supplement",
        "clinic"
      ]
    },
    {
      name: "Transport",
      color: "#5f7e9b",
      keywords: [
        "fuel",
        "gas",
        // Whole-token matching means "gas" no longer covers this on its own.
        "gasoline",
        "parking",
        "uber",
        "lyft",
        "transit",
        "metro",
        "toll",
        "car wash",
        "bus",
        "train",
        "taxi",
        "airfare",
        "rideshare",
        "oil change"
      ]
    },
    {
      name: "Personal",
      color: "#b8788a",
      keywords: [
        "shirt",
        "socks",
        "cosmetic",
        "lotion",
        "beauty",
        "skincare",
        "hair",
        "gift",
        "jeans",
        "shoes",
        "jacket",
        "makeup",
        "perfume",
        "razor",
        "clothing"
      ]
    },
    {
      name: "Entertainment",
      color: "#7fa7a3",
      keywords: [
        "movie",
        "book",
        "game",
        "ticket",
        "music",
        "stream",
        "toy",
        "concert",
        "theater",
        "museum",
        "bowling",
        "arcade",
        "subscription"
      ]
    },
    {
      name: "Other",
      color: "#a9a196",
      keywords: []
    }
  ];
}
